services:

  app: &app
    build:
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
      context: .
      dockerfile: docker/dockerfiles/app.dockerfile
      target: development
      tags:
        - "demo-blog.app.dev"
    tty: true
    stdin_open: true
    entrypoint: /docker/entrypoints/app-entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/usr/local/bundle/gems
    env_file:
      - ./docker/.env.development

  worker:
    <<: *app
    entrypoint: /docker/entrypoints/worker-entrypoint.sh
    depends_on:
      - app
      - redis
    ports: []
    volumes:
      - gem_cache:/usr/local/bundle/gems

  db:
    image: postgres:16.2
    privileged: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./docker/.env.development

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

volumes:
  db-data:
  gem_cache:
    driver: local
    driver_opts:
      type: none
      device: ./vendor/bundle
      o: bind
